

CREATE SEQUENCE SEQ_USER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE USERS (
    USER_SEQ    NUMBER      NOT NULL,
    GENDER      NUMBER(1)   NOT NULL,
    AGE_GROUP   NUMBER(1)   NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_SEQ)
);


CREATE TABLE ECONOMY (
    USER_SEQ        NUMBER      NOT NULL,
    INCOME_GROUP    NUMBER(1)   NOT NULL,
    FAMILY_TYPE     NUMBER(1)   NOT NULL,
    CONSTRAINT PK_ECONOMY PRIMARY KEY (USER_SEQ),
    CONSTRAINT FK_ECONOMY_USERS FOREIGN KEY (USER_SEQ) REFERENCES USERS(USER_SEQ)
);


CREATE TABLE SUBSCRIPTION (
    USER_SEQ            NUMBER      NOT NULL,
    MONTHLY_FEE_CODE    NUMBER(1),
    HAS_AD_PLAN         NUMBER(1),
    AD_INTENT           NUMBER(1),
    CONSTRAINT PK_SUBSCRIPTION PRIMARY KEY (USER_SEQ),
    CONSTRAINT FK_SUBSCRIPTION_USERS FOREIGN KEY (USER_SEQ) REFERENCES USERS(USER_SEQ),
    CONSTRAINT CHK_AD_INTENT CHECK (AD_INTENT BETWEEN 1 AND 5 OR AD_INTENT IS NULL)
);


CREATE TABLE USAGE_BEHAVIOR (
    USER_SEQ            NUMBER      NOT NULL,
    USE_FREQUENCY       NUMBER(1),
    WEEKDAY_TIME_CODE   NUMBER(1),
    WEEKEND_TIME_CODE   NUMBER(1),
    USED_LAST_WEEK      NUMBER(1),
    AVG_MIN_WEEKDAY     NUMBER(5,1),
    AVG_MIN_WEEKEND     NUMBER(5,1),
    SEARCH_VIEW         NUMBER(1),
    RECOMMEND_VIEW      NUMBER(1),
    BINGE_WATCH         NUMBER(1),
    CONSTRAINT PK_USAGE PRIMARY KEY (USER_SEQ),
    CONSTRAINT FK_USAGE_USERS FOREIGN KEY (USER_SEQ) REFERENCES USERS(USER_SEQ)
);


CREATE TABLE USER_OTT_SERVICE (
    USER_SEQ        NUMBER      NOT NULL,
    SERVICE_CODE    NUMBER(2)   NOT NULL,
    CONSTRAINT PK_USER_OTT_SERVICE PRIMARY KEY (USER_SEQ, SERVICE_CODE),
    CONSTRAINT FK_OTT_SERVICE_USERS FOREIGN KEY (USER_SEQ) REFERENCES USERS(USER_SEQ)
);


CREATE TABLE USER_DEVICE (
    USER_SEQ        NUMBER      NOT NULL,
    DEVICE_CODE     NUMBER(1)   NOT NULL,
    CONSTRAINT PK_USER_DEVICE PRIMARY KEY (USER_SEQ, DEVICE_CODE),
    CONSTRAINT FK_USER_DEVICE_USERS FOREIGN KEY (USER_SEQ) REFERENCES USERS(USER_SEQ)
);


CREATE TABLE USER_CONTENT_TYPE (
    USER_SEQ        NUMBER      NOT NULL,
    CONTENT_CODE    NUMBER(1)   NOT NULL,
    CONSTRAINT PK_USER_CONTENT PRIMARY KEY (USER_SEQ, CONTENT_CODE),
    CONSTRAINT FK_USER_CONTENT_USERS FOREIGN KEY (USER_SEQ) REFERENCES USERS(USER_SEQ)
);


CREATE TABLE USER_BROADCAST_TYPE (
    USER_SEQ            NUMBER      NOT NULL,
    BROADCAST_CODE      NUMBER(1)   NOT NULL,
    CONSTRAINT PK_USER_BROADCAST PRIMARY KEY (USER_SEQ, BROADCAST_CODE),
    CONSTRAINT FK_USER_BROADCAST_USERS FOREIGN KEY (USER_SEQ) REFERENCES USERS(USER_SEQ)
);
